sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product sqr-038
env:
  global:
    -
      # LTD_AWS_ID
      secure: P+mguzGm8VZ2UUpqrVnMYgrYr7X33f/KGQ2ZOkby3tTLK4a+C7hYDArtwf92NC0wMcXi6P9tOqcYx8ISD6nGonE4aCyTppkvCBFmnBONbqFVy0wD1ZJVDFCz0NYvXebUxKjbSS2SS+80R3IZIU8bekR15IKaoItaXzWrK6esnH8NVd5icrIN+xoCeme0jv2Axa0WGZyfupO3i5sO9GVyg1kKqPJtKQq5GmC5xhJ05j2RJVZKKGNxGTTL1oRS46VYBMXxCI8y1ZnymOBC9zglZuRn6elP0wDw93aV1SU1rF+pT4D4RHtsLMGPWosLRhY4Lk/KnQthzAr0lpAXDwoWrWU9563erVBrkBgKXTj9cGWwU5wG0kmWSq9dVROdLr9pDXSsizkVnNKCyCfUULn3pwxPTxOd1BYBXXoInvpgCscsZXSFw+SfUrCY5iuY5MHCi6e0M7YGkwfs1a4tVMXYu7TmDieSSm/28l/SM++AnrQTUgeMkohh1+WillT9XuZIapfLtnwb1nW9VDhP2GQ3+7ahgD6qrusZTPyP5Ha7cwPlkov1T0MAi7z412PNv/16eDJbFn9rWUblc+pZRZUv5O1n7HdAMWzqem+nEPOMOJX8OFTJ+z+NfsvqAxrgCeKYLi+B1S71j0ojPwGyiBMOgvbaZonnVC7fkN6w+/Im0MY=
    -
      # LTD_AWS_SECRET
      secure: kiwUtRnqXpfwmrm5eZTs9xmAhJ9POwBlghM4V00f1irs7+IEoW7R/ObEC5PYp2DSv7tRrt2PETSIIo4szFa0QPU//QguwN7xfpE1+7w5/dP4TSTpC4wlJY8Y8NGVrXY5zvU6OL5h3+60efN3q5pttxEVlcDz1/06wG92WVqvsCNNJmmEHiUfCWqHzcvpxlC6cWlZ3VnHTmjPPxtiqPA5XjgE6Sx7BpaBtx+4yBusyKpyudR3NeiZmbR/b1fr4cb63dKeLAoTcZsg7zwUB1qfWTgSoWdJIBKTWP4kEER06tjM64tsxVS/VN2C4yzbGtpG7MVq29Wx/7rZwJ5MgA3jlRV7FMPQ/USPSV4sxhak9YVB2PiSv04Zo2vt6JT4Cvx4H/CT97NO79ON/sYTEK6h4BVsRRq9XX41v45jolOsZzvyQ1ouBn5s299PPVFHqbksMLX1fJvfrIIr+QRNTXysgc2m57QuoGLoAznM+Bldci43FAaBhj8p55BkROhfG34We5b/Cv9/j5FH6i25QEqexlM9ycqi0M903IJ0yB4FzkEC8l1AiCiD+T1wHkYIqdYCJYUybTBfzEDUBXLY5LbifovHQh84YH9FvrS5MTlexY46mRl3ntrmB9E0OY+2Lwdx24b297bFwMi1OoFiyaCSG3MLDzfUNusqfhkEOtOflj0=
    -
      # LTD_USERNAME
      secure: EvLMo9fMha/bVML5VYcnhIkU9RN92zEM3Kv2Ubnfm42I16CbgVdyTuPeFsTqlIZWzk4jW6UWQNR2tRCcInIlFgtB8erKeOxUGl18X73dwphFuCRZXvwS1WtFo/FsioJYFbaAwZcM6fMZvNrBzUKH+31jopqXvpqTpTpEoq7S25xRdnMr6OCwCjSdxFtCOQoHBowJd7NH/kGqa8UoRF5DJHXySsl/S8BQCGeBaUULxN4cPCMmdncUpCxXCTa8qeJf0dKvRWAO1+5B4mFuwfQV8EwtPeIhE3WAkHkWrlp4woyRCkyudVQmi8moYk83VCWUDLnESZJwcShFRv5NhPBFVTim4KI52/MZewW1nCibGT46RzDTAqgi0Dz+5PwNnsjc/kcikt+Pt63djJez2JYXQB0WgUgW8VInv88tGqShf5zGA9+9GSmdOjWvImoUZ6nQf5Lc3D4BXygzExx52dDNKigAlNJm19AY8WbOgqSZKHfvquxZ8karLRYwksDGrUV+Ory9iucDm53yKzLG1oqODOqHFvJa99MShk5NITZRanqRr1ldCQikzroWpqTaWNFTSCFpIYKBd4n/WWK9MQIOA1pAryZVMxQ+OXWHSB3bRfpBu4MM5PuWYUk2ob418o37SW0omvHrkgnsxQXfR3dHxJAhVjA3gVsP9GLLXKDlG8U=
    -
      # LTD_PASSWORD
      secure: Ep9oFSdFCpKCfBP7/cjowYGw8EoMqJMN2mhE1EyLsjBZYRvkHzRNQo7bm9SfOWwLlLYEhTRvjSUhumGMThgdF+8/rrtH0ZGZbO/14b9j+rDtH4NMlJqpDdIdAJxFnRVJuwkmehm4kyS5tC9J9xhYu83rkSNFJB0grrNq/wFUPgoAyzHighJdEIc5Ft/UVtkG84jMiH2KmepcZ9hpLQjGi6THyLq5uOWRwXtj04VjZs8y5frzjq9fd8ek2HHJe7VjbRLZlli9DNiMlZzhNsmkt/XgLg4JvF4kddnvQvjlkh1B0DfQwfPBt4M++Q6fx1Lbb8WzQdCYf8YmjuPu75J+AotOPEOBI+d0AYubxcdCXzCVNW2diBXQ3e91Q4ZbPBAaw1hxsM/VW9akFTLtge+h++Du3tn05Vc4nDxgeGHvwW77UExmLlIcxCs6JBCuf5l57MynRdkMn9ZvzzUgT35a+0jv3VlgMp7cfTzvqja7X8O1DAP6FoCZBGss22D22Le+B7kA5VjKrer9MJpcxJGLBTyNtOqtHtuDYXdL1LpKDKt6rVgLYT1NkKuT9FpbyUDT89LbiQBJnqpgC/wayi9xQOb28LHWxU5+NIWgMXMYvaJ4oEhVfHjTLsmosgHCU+27PVpRL9MG6FeH+/uf3tIj4ukV3JxewjRxjuEEDFZ1VQ8=
